### ISSUE TITLE
Add spellcheck

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-topics#15]
We need to add a spellchecker to the deliberation-topics GitHub actions to check our topic documentation for spelling errors. 

Task List:

- [x] Find spellcheck action to implement in our repo
- [x] Get spellcheck to run
- [x] Make sure to add obscure/undefined words from our repo to the word library
- [x] Fix spelling errors in markdown files and get the folder to clear the spellcheck

**Comment by isaacgat** [comment]
Kimberly and I found a spellcheck action online: https://github.com/rojopolis/spellcheck-github-actions and worked to add it to the repo. After a bit of toying around with the parameters, we got it to work and were able to fix our spelling errors and add some unique words to the word library. In the end, our topic markdowns passed the spellcheck. 

Important: we learned that we need to include URL's in an HTML tag in the README.md so we could exclude anything within an HTML tag from the spellcheck. This made it so words without spaces were not being unnecessarily flagged by the spellcheck.
