### ISSUE TITLE
Add question answer choices to ANES topics

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-topics#16]
The way the topics from the ANES are written, each topic can have a unique set of responses. We want our answer choices to match this pattern, and be something we can programmatically ask as a question both prior to and during a discussion. We should expand the current topic descriptions from the anes. They currently are formatted as:

```markdown
# Federal spending on aid to the poor

## Prompt
What about aid to the poor? Should federal spending on aid to
the poor be increased, decreased, or kept the same?
```

we can create a separate section to contain the original response options as similar to:

```markdown
# Federal spending on aid to the poor

## Prompt
What about aid to the poor? Should federal spending on aid to
the poor be increased, decreased, or kept the same?

## Responses
- Increased
- Kept the Same
- Decreased
```

Lets start by doing this for 5 topics and trying it out to see how it works.

**Comment by isaacgat** [comment]
I'm going to pick one topic of each type (Economic, Moral, Civil Rights, Security, and Non-Partisan) that offers 5 choices for responses.

**Comment by isaacgat** [comment]
- Economic: fs_welfare (federal spending on border security seemed more divisive but that toes the line of security... this question is more geared towards specifically the economy)
 - Moral: climate_chng_importance 
 - Civil Rights: worry_less_abt_eqlty (Questions asking specifically about inequality of Black people had higher variances and polarity but I'm worried that people will not be open with their true opinions if asked these questions in front of others. This effect may be worth studying down the line but this question about general equality may be better suited for this test drive.) 
- Security: protesters_actions (Question may have a different connotation in 2022 as opposed to 2020) 
- Nonpartisan: trust_washington

**Comment by isaacgat** [comment]
I updated these issues in the topics repo. Waiting on PR approval.
