### ISSUE TITLE
Research literature to determine the variance and partisan split of political issues

### ISSUE THREAD

**Issue by isaacgat** [Watts-Lab/deliberation-topics#4]
As we set up our deliberations, we need to understand the implications of the topics we give our group members. Doing so will require making a catalog of political topics that span across two different spectrums: 1.) variance and 2.) partisan split. The former describes how varied responses are across the population (e.g., we can expect a wide variety of answers to the question "What is your favorite month?" and a low variety of answers to the question "Is murder wrong?"). The latter describes how sorted opposing opinions are across party lines (e.g., we expect a weak partisan split for permanent daylight savings time and a strong split for abortion rights). 

It is important to point out that these two metrics are not necessarily the same. For instance, a topic can be both high in variance and completely unrelated to partisan divide (e.g., a favorite month). 

By referring to this catalog of topics, we can assign a variety of topics to different groups before testing our interventions. And if our interventions only work in some cases, we should be able to say, for example, "XYZ intervention only works when groups are dealing with topics of XYZ variance and XYZ partisan divide. 

To-Do List:

- [ ] Revisit the falsifying deliberative democracy paper and find papers that cited that paper to check for methodology
- [x]  Read Baldassari and Gelman’s paper and review the questions used in their study
- [ ]  Read Issue alignment and partisanship in the American public and go over questions they pulled from ANES
- [x]  Look at reproduction scripts and see how they dealt with questions of different types of responses (3/5/7) 
- [x] Analyze data from GSS and/or ANES to determine the breakdown of issues and calculate variance in spite of response differences
- [x] Create a metric for measuring partisan divide (-1 to 1 scale?)
- [ ] Create a catalog of topics that plots issues along both axes in terms of variance and partisan divide. 
- [x]  Decide how to pick questions (maybe just by variance and don't worry about party for now?)

**Comment by JamesPHoughton** [comment]
Broke out a part of this into its own issue here: https://github.com/Watts-Lab/deliberation-topics/issues/7 for this week.
